### ISSUE TITLE
Can it be used with the 23H2 system's Copilot?

### ISSUE THREAD

**Issue by HsiaoCH** [MicrosoftDocs/mslearn-copilot-plugins#2]
I came across the article 'Plugins for Microsoft Copilot/ Sideload and test plugins (Private Preview),' which discusses the method of importing and testing plugins in the Bing browser. This sparked my curiosity about whether there is a similar capability for importing and testing plugins in the Copilot system on the device. I wanted to inquire if you provide a way to import plugins into the Copilot system and if so, what is the correct method for doing so?

Additional question:
In the past few days, I noticed that the location for importing plugins in Bing (the wrench icon) has disappeared, preventing me from testing plugins with Bing. Could you please let me know the current location for importing plugins in Bing?

Thank you.

**Comment by captainbrosset** [comment]
Thanks for reaching out about this.

> I came across the article 'Plugins for Microsoft Copilot/ Sideload and test plugins (Private Preview),' which discusses the method of importing and testing plugins in the Bing browser. This sparked my curiosity about whether there is a similar capability for importing and testing plugins in the Copilot system on the device. I wanted to inquire if you provide a way to import plugins into the Copilot system and if so, what is the correct method for doing so?

I'll ask and get back to you on this as soon as I know more.

> Additional question: In the past few days, I noticed that the location for importing plugins in Bing (the wrench icon) has disappeared, preventing me from testing plugins with Bing. Could you please let me know the current location for importing plugins in Bing?

The wrench icon should still be there. If it disappeared for you, it could mean that you don't have access to it. Note that sideloading is currently in private preview, as described on https://learn.microsoft.com/en-us/copilot-plugins/test-debug/sideload-test-plugins

**Comment by HsiaoCH** [comment]
The online information regarding the "Bing Plugin" is very limited, so I appreciate your response very much.

I would like to ask if there is currently a method to enable this permission. (I have searched for permission-related content before asking, but to no avail.) I cannot find relevant settings in my account configuration. Currently, I have no intention to publish; I only want to use a local server to test the plugin.

> The wrench icon should still be there. If it disappeared for you, it could mean that you don't have access to it.

**Comment by captainbrosset** [comment]
There is currently no way to enable the experience. We are planning to get sideloading out of private preview over the coming weeks, no precise date to share yet however.

**Comment by HsiaoCH** [comment]
Okay, I got it. Thank you for your response.
