### ISSUE TITLE
Question about the article "Test and debug an API plugin"

### ISSUE THREAD

**Issue by HsiaoCH** [MicrosoftDocs/mslearn-copilot-plugins#6]
Hi, about half a year ago, I asked about the issue of the "Test a plugin button" not existing. At that time, I wanted to test my plugin, but since there was no "Test a plugin button," I couldn't test it.

Recently, I checked the status of Copilot, and the "Test a plugin button" is still missing. I have the following questions:

- It was previously mentioned that my account might not have sufficient permissions. Is there a way to request the necessary permissions?

- Are there any other methods to test the plugin?

- I recently discovered that the new Copilot Studio seems to have features related to plugin development and testing. Is this related to the plugin mentioned in the article "Test and debug an API plugin"?

Since I'm not sure how to properly ask questions regarding articles on "learn.microsoft," I'm raising these questions here. If my way of asking is incorrect, please let me know. Thank you.

**Comment by captainbrosset** [comment]
Thank you for reaching out. This is a good place to discuss about Copilot API plugins, specifically in "web" surfaces like Copilot in Edge, Copilot in Bing, and copilot.microsoft.com.

Unfortunately, we're not currently planning on opening up the ability to test and debug API plugins as a public preview at this stage. We'll make sure to update our documentation and samples as our plans evolve.

If you are interested in Copilot plugins in the scope of Microsoft 365, then I suggest going through the [Extensibility options for Microsoft Copilot for Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365-copilot/extensibility/decision-guide).
